version: "3"
services:
  laravel:
    tty: true
    image: bitnami/laravel:7
    container_name: laravel_container
    ports:
      - 8005:8005
    volumes:
      - ./backend/laravel:/app
    command: >
      bash -c " composer install
      && php artisan route:list
      && php artisan migrate
      && php artisan key:generate
      && php artisan jwt:secret --no-interaction
      && php artisan serve --host=0.0.0.0 --port=8005 "
    depends_on:
      - database
      - redis
    networks:
      - servidor_network

  web:
    image: golang:1.15
    container_name: go_container
    working_dir: /go/src/goApp
    volumes:
      - ./backend/go:/go/src/goApp
    command: >
      bash -c " rm -f go.mod || true
      && rm -f go.sum || true
      && go mod init goApp
      && go mod tidy
      && go get github.com/pilu/fresh
      && fresh "
    ports:
      - "3000:3000"
    labels:
      traefik.backend: "web"
      traefik.frontend.rule: "PathPrefix:/"
    depends_on:
      - database
      - redis
    networks:
      - servidor_network

  songs:
    image: golang:1.15
    container_name: go_songs_container
    working_dir: /go/src/goSongs
    volumes:
      - ./backend/go/songs:/go/src/goSongs
    ports:
      - "3001:3001"
    command: >
      bash -c " rm -f go.mod || true
      && rm -f go.sum || true
      && go mod init goSongs
      && go mod tidy
      && go get github.com/pilu/fresh
      && fresh "
    labels:
      traefik.backend: "songs"
      traefik.frontend.rule: "PathPrefix:/"
    depends_on:
      - database
      - redis
    networks:
      - servidor_network

  database:
    image: mysql:5.7
    container_name: database_container
    environment:
      - "MYSQL_DATABASE=laravel_go"
      - "MYSQL_ROOT_PASSWORD=laravel_go"
      - "MYSQL_USER=laravel_go"
      - "MYSQL_PASSWORD=laravel_go"
    volumes:
      - ./mySqlBackup:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - servidor_network

  redis:
    image: redis:4.0
    container_name: redis_container
    volumes:
      - redisData:/data
    ports:
      - "6379:6379"
    networks:
      - servidor_network

  traefik:
    image: traefik:v2.3
    container_name: traefik_container
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    networks:
      - servidor_network
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus_container
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    depends_on:
      - traefik
    links:
      - traefik
    networks:
      - servidor_network
    command: --config.file=/etc/prometheus/prometheus.yml
  grafana:
      depends_on:
          - prometheus
      ports:
          - "3500:3000"
      container_name: grafana_container
      image: "grafana/grafana:7.1.5"
      environment: 
          - GF_AUTH_DISABLE_LOGIN_FORM=true
          - GF_AUTH_ANONYMOUS_ENABLED=true
          - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
          - GF_INSTALL_PLUGINS=grafana-clock-panel 1.0.1
      networks: 
          - servidor_network
      volumes:
          - "myGrafanaVol:/var/lib/grafana"
          - "./grafana:/etc/grafana/provision/datasources"
networks:
  servidor_network:

volumes:
  myGrafanaVol:
  redisData: